wget -N --content-disposition http://gimpchat.com/download/file.php?id=58192
wget -N --content-disposition http://gimpchat.com/download/file.php?id=61458
wget -N --content-disposition http://gimpchat.com/download/file.php?id=61578
wget -N --content-disposition http://gimpchat.com/download/file.php?id=61561
wget -N --content-disposition http://gimpchat.com/download/file.php?id=61544
wget -N --content-disposition http://gimpchat.com/download/file.php?id=61185
wget -N --content-disposition http://gimpchat.com/download/file.php?id=61181
wget -N --content-disposition http://gimpchat.com/download/file.php?id=61343
wget -N --content-disposition http://gimpchat.com/download/file.php?id=58452
wget -N --content-disposition http://gimpchat.com/download/file.php?id=61474
wget -N --content-disposition http://gimpchat.com/download/file.php?id=57059
wget -N --content-disposition http://gimpchat.com/download/file.php?id=56987
wget -N --content-disposition http://gimpchat.com/download/file.php?id=56107
#pag2
wget -N --content-disposition http://gimpchat.com/download/file.php?id=61481
wget -N --content-disposition http://gimpchat.com/download/file.php?id=61531
wget -N --content-disposition http://gimpchat.com/download/file.php?id=61178
wget -N --content-disposition http://gimpchat.com/download/file.php?id=57036
wget -N --content-disposition http://gimpchat.com/download/file.php?id=61475
wget -N --content-disposition http://gimpchat.com/download/file.php?id=56453
wget -N --content-disposition http://gimpchat.com/download/file.php?id=61177
wget -N --content-disposition http://gimpchat.com/download/file.php?id=58007
wget -N --content-disposition http://gimpchat.com/download/file.php?id=54664
wget -N --content-disposition http://gimpchat.com/download/file.php?id=61111
#pag3
wget -N --content-disposition http://gimpchat.com/download/file.php?id=57751
wget -N --content-disposition http://gimpchat.com/download/file.php?id=61006
wget -N --content-disposition http://gimpchat.com/download/file.php?id=59863
wget -N --content-disposition http://gimpchat.com/download/file.php?id=61530
wget -N --content-disposition http://gimpchat.com/download/file.php?id=56108
wget -N --content-disposition http://gimpchat.com/download/file.php?id=61482
wget -N --content-disposition http://gimpchat.com/download/file.php?id=60576
wget -N --content-disposition http://gimpchat.com/download/file.php?id=61266
wget -N --content-disposition http://gimpchat.com/download/file.php?id=61509
wget -N --content-disposition http://gimpchat.com/download/file.php?id=58671
wget -N --content-disposition http://gimpchat.com/download/file.php?id=61034
wget -N --content-disposition http://gimpchat.com/download/file.php?id=57906
#pag4
wget -N --content-disposition http://programmer97.byethost10.com/Files/arrow.zip